[package]
name = "procfs"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "Apache 2.0"
include = ["src/lib.rs"]

[dependencies]
procfs-thrift = { path = "if" }
lazy_static = "1.0"
libc = "0.2"
openat = "0.1.18"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.1"
