[package]
name = "below"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "Apache 2.0"
include = ["src/**/*.rs"]

[dependencies]
below-thrift = { path = "if" }
cgroupfs = { path = "../common/cgroupfs" }
procfs = { path = "../common/procfs" }
fbthrift = { git = "https://github.com/facebook/fbthrift.git", branch = "master" }
slog_glog_fmt = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
async-trait = { version = "0.1", features = ["support_old_nightly"] }
chrono = { version="0.4", features=["serde"] }
cursive = "0.14.0"
futures-preview = { package = "futures", version = "0.3", features = ["async-await", "compat"] }
hostname = "0.3"
humantime = "1.3"
libc = "0.2"
maplit = "1.0"
memmap = "0.7"
nix = "0.15"
once_cell = "1.2"
rand = { version = "0.7", features = ["small_rng"] }
serde_json = "1.0"
slog = { version="2.5", features=["max_level_debug"] }
slog-async = "2.3"
slog-term = "2.4.2"
structopt = "0.3.7"
tempdir = "0.3"
tokio-preview = { package = "tokio", version = "0.2", features = ["full"] }
walkdir = "2.2.9"
