name: dockerhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_push:
    if: github.repository == 'facebookincubator/below'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: >
        docker build
        -t below
        .
    - name: Tag docker image
      run: docker tag below below/below:latest
    - name: Authenticate with docker registry
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - name: Push docker image
      run: docker push below/below:latest
